### ISSUE TITLE
Bug correction: Downloading Indian Pines fails

### ISSUE THREAD

**Issue by cohenjer** [benchopt/benchmark_nmf#7]
When downlading the Indian Pines dataset during the `benchopt run` command, we get the following error:
`<urlopen error [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1131)>`

The download relies on the following code snippet:
```python
url = "http://www.ehu.eus/ccwintco/uploads/6/67/Indian_pines_corrected.mat"
r = urlopen(url)
Xtensor = scipy.io.loadmat(BytesIO(r.read()))["indian_pines_corrected"]
```

This is a known error, and e.g. [this post](https://stackoverflow.com/questions/71603314/ssl-error-unsafe-legacy-renegotiation-disabled) suggests to downgrade the cryptography package in Python.

Typing the following in the console inside the benchmark_nmf conda environment fixed the problem for me:
`
 conda install cryptography==36.0.2
`

However, when adding to indian_pines.py the following requirements:
```python
install_cmd = 'conda'
requirements = ['pip:cryptography==36.0.2']
```
upon installation of the benchmark no issue is raised, but the previous SSL error remains. Most likely the requirements is not correctly written.

**Comment by cassiofragadantas** [comment]
PR #9 is a quick fix. It allows to use the dataset without errors for now.
Maybe a different way to load the dataset should be considered in the future.
